### ISSUE TITLE
Handler

### ISSUE THREAD

**Issue by InFlames513** [memte/v14-slash-command-handler#3]
Handleri obje olarakda gönderebilirsin neden bu kadar uzattın ki çok daha kısa bir handler yapabilirsin 👌

**Comment by memte** [comment]
Komut oluştururken ki yeri bahsediyorsun sanırım. Açıkçası daha çok docslara yönelik olması açısıyla bunu tercih ettim. Ha obje şeklinde de yapilabilir. Bunun için ayri bi reposunu açabilirim kullanmak istiyenler için fakat bunlar zaten ayni şeyi döndürüyor açıkçası hiç farketmiyecek 😉

**Comment by memte** [comment]
Bunun o kadarda uzun olduğunu da hiç sanmıyorum 🤔
